apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-deployment
  labels:
    app: demo
  namespace: production    
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 1
  selector:
    matchLabels:
      app: demo
  template:
    metadata:
      labels:
        app: demo
    spec:
      containers:
      - name: demo
        image: metaplan.azurecr.io/gdc/metaplan/g_metaplan_rat_be_aks:v.0.0.61
        # env:
        # - name: BE_POSTGRES_HOST
          # value: "postgres-prd"
        # - name: BE_POSTGRES_PORT
          # value: "5432"          
        # - name: BE_POSTGRES_USERNAME
          # value: "postgres"
        # - name: BE_POSTGRES_PASSWORD
          # value: "Metanet@12345"
        ports:
        - containerPort: 8080
        readinessProbe:
          httpGet:
            path: /search?message=abaasass
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 5
          successThreshold: 1
