apiVersion: v1
kind: Service
metadata:
  name: demo-service
  labels:
    app: demo
  annotations:
    konghq.com/protocol: "https"
  namespace: production  
spec:
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30013
  selector:
    app: demo
